from .azure import AzureWorker
from .baichuan import BaiChuanWorker
from .base import *
from .claude import ClaudeWorker
from .fangzhou import FangZhouWorker
from .gemini import GeminiWorker
from .minimax import MiniMaxWorker
from .qianfan import QianFanWorker
from .qwen import QwenWorker
from .tiangong import TianGongWorker
from .vivo import VivoWorker
from .xinghuo import XingHuoWorker
from .zhipu import ChatGLMWorker
